services:
  - type: web
    name: raahione-backend
    env: docker
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false